In [2]:
# Import basics

import torch
import torch.nn as nn
import torch.optim as optim

In [3]:
# Create dummy dataset

X = torch.tensor([[1.0, 2.0],
                  [2.0, 3.0],
                  [3.0, 4.0],
                  [4.0, 5.0]])

y = torch.tensor([[3.0],
                  [5.0],
                  [7.0],
                  [9.0]])

In [4]:
# Define neural network

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2,4)
        self.fc2 = nn.Linear(4,1)

    def forward(self, x):
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc2(x)
        return x

In [5]:
# Create model + loss + optimizer

model = SimpleNN()

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)


In [6]:
# Traning loop

for epoch in range(100):

    predictions = model(X) #forward pass

    loss = criterion(predictions, y) #compute loss

    #backprop
    optimizer.zero_grad()
    loss.backward()

    #update weights
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")



Epoch 0, Loss: 34.68836212158203
Epoch 10, Loss: 0.22720244526863098
Epoch 20, Loss: 0.20020277798175812
Epoch 30, Loss: 0.17656342685222626
Epoch 40, Loss: 0.15580590069293976
Epoch 50, Loss: 0.13753663003444672
Epoch 60, Loss: 0.12142910063266754
Epoch 70, Loss: 0.10720904171466827
Epoch 80, Loss: 0.09464295208454132
Epoch 90, Loss: 0.08353176712989807


In [7]:
# Print Learned Weights

print(model.fc1.weight)
print(model.fc1.bias)

print(model.fc2.weight)
print(model.fc2.bias)


Parameter containing:
tensor([[ 0.1883,  0.2056],
        [-0.5311,  0.0209],
        [ 0.3591,  1.2094],
        [-0.5883, -0.4653]], requires_grad=True)
Parameter containing:
tensor([-2.1040e-04, -5.1625e-01, -1.3561e-02,  5.7263e-01],
       requires_grad=True)
Parameter containing:
tensor([[ 0.2070, -0.3362,  1.0765,  0.1583]], requires_grad=True)
Parameter containing:
tensor([0.3322], requires_grad=True)


In [8]:
new_data = torch.tensor([[1.0, 3.0], [3.1, 4.7]])

model.eval()

with torch.no_grad():

    prediction = model(new_data)

    print(prediction)

tensor([[4.7767],
        [7.9560]])


In [9]:
from torchview import draw_graph

graph = draw_graph(
    model,
    input_size=(1, 2),
    expand_nested=True
)

graph.visual_graph

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH